name: NODE-JS

on: [workflow_dispatch, push]

permissions: read-all

concurrency: 
  cancel-in-progress: false

  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4 # Uses v4 which runs on Node 24
        with:
          languages: 'javascript-typescript'
          build-mode: none 

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4

      - name: install dependencies
        run: npm install

      - name: run
        run: npm run build --if-present

      - name: test
        run: echo "test is passed"

      - name: Artifact upload 
        uses: actions/upload-artifact@v7
        with:
           name: artifact-1
           path: |
              package*




